# ============================================================
# Production Environment
# ============================================================

base.url=https://example.com

api.base.url=https://api.example.com
integration.test.url=https://example.com

environment.name=prod
aut.base.url=https://www.saucedemo.com