# ============================================================
# QA Environment
# ============================================================

base.url=https://qa.example.com

api.base.url=https://qa-api.example.com
integration.test.url=https://example.com

environment.name=qa
# ============================================================
# Application Under Test
# ============================================================

aut.base.url=https://www.saucedemo.com