# ============================================================
# Staging Environment
# ============================================================

base.url=https://staging.example.com

api.base.url=https://staging-api.example.com
integration.test.url=https://example.com

environment.name=staging

aut.base.url=https://www.saucedemo.com